version: '3.8'

services:

  app:
    build: .
    container_name: gitinsight-app
    ports:
      - "8080:8080"
    depends_on:
      - ollama
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gitinsight
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
      - ./init-ollama.sh:/init-ollama.sh
    entrypoint: ["/bin/sh", "/init-ollama.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 10s
      retries: 5

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: gitinsight
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  ollama-data:
  pg-data: