version: '3.8'

services:

  app:
    build: .
    container_name: gitinsight-app
    ports:
      - "8080:8080"
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
      - ./init-ollama.sh:/init-ollama.sh
    entrypoint: ["/bin/sh", "/init-ollama.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 10s
      retries: 5

volumes:
  ollama-data: