spring:
  ai:
    ollama:
      base-url: http://ollama:11434
      chat:
        model: qwen2.5-coder:3b
  application:
    name: gitinsight.ai

integration:
  github:
    base-url: https://api.github.com
    token: ${GITHUB_TOKEN:}