spring:
  application:
    name: gitinsight.ai
  ai:
    ollama:
      base-url: http://ollama:11434
      chat:
        model: qwen2.5-coder:3b
  main:
    lazy-initialization: true

integration:
  github:
    base-url: https://api.github.com